mutation CreateLesson($title: String!) {
  createLesson(title: $title) {
    id
    title
  }
}

mutation UpdateLesson($lessonId: String!, $input: LessonInput!) {
  updateLesson(lessonId: $lessonId, input: $input) {
    id
  }
}
