query LessonPage($lessonId: String!) {
  lesson(lessonId: $lessonId) {
    id
    title
    description
    pictureUrl
    markdownContent
    totalDuration
    userProgress
    updatedAt

    teacher {
      id
      firstName
      lastName
      fullName
    }

    chapters {
      id
      position
      title
      isQuizCompletedByUser
      isVideoWatchedByUser
      hasQuestions
    }
  }
}
