version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: database
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    ports:
      - 5432:5432
  minio:
    image: docker.io/bitnami/minio:2023
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    restart: on-failure
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
      MINIO_BUCKET: ${MINIO_BUCKET}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio password;
      /usr/bin/mc mb myminio/${MINIO_BUCKET};
      /usr/bin/mc admin user svcacct add myminio minio --access-key ${MINIO_ACCESS_KEY} --secret-key ${MINIO_SECRET_KEY};
      exit 0;
      "

volumes:
  minio_data:
    driver: local
  minio_config:
    driver: local
