query TeacherHomePage($userId: String) {
  user(userId: $userId) {
    lessons {
      markdownContent
      id
      description
      pictureUrl
      title
      totalDuration
      updatedAt
    }
  }
}
