query Chapter($chapterId: String!) {
  chapter(chapterId: $chapterId) {
    id
    order
    title
    markdownContent
    updatedAt
    videoUrl
    videoDuration
    isQuizCompletedByUser
    isVideoWatchedByUser
    userVideoWatchProgress
    hasQuestions
    questions {
      id
      question
      answers
      correctAnswer
    }
    lesson {
      id
    }
  }
}
