query TeacherLessonsPage($lessonId: String!) {
  lesson(lessonId: $lessonId) {
    chapters {
      id
      position
      title
      markdownContent
      updatedAt
      videoUrl
      videoDuration
      isQuizCompletedByUser
      isVideoWatchedByUser
      userVideoWatchProgress
      hasQuestions

      questions {
        id
        question
        answers
        correctAnswer
      }

      comments {
        id
        content
        createdAt
        deletedAt

        author {
          fullName
          id
        }
      }
    }
    description
    id
    markdownContent
    pictureUrl
    title
    totalDuration
    updatedAt
    userProgress
  }
}
