type Chapter {
  id: ID!
  "An integer representing the order of the chapter in the lesson."
  order: Int!
  title: String!
  "A description of the chapter content or presentation - in markdown format."
  markdownContent: String
  updatedAt: DateTime!

  # Computed
  videoUrl: String
  "Duration of the video in seconds."
  videoDuration: Int
  isQuizCompletedByUser: Boolean!
  isVideoWatchedByUser: Boolean!
  "Percentage of video watched by user"
  userVideoWatchProgress: Int!
  hasQuestions: Boolean!

  # Relations
  lesson: Lesson!
  questions: [Question!]!
  comments: [Comment!]!
}

input ChapterInput {
  title: String!
  "A description of the chapter content or presentation - in markdown format."
  markdownContent: String
  "Duration of the video in seconds."
  videoDuration: Int!
  questions: [QuestionInput!]!
}
