type Lesson {
  id: ID!
  title: String!
  description: String
  pictureUrl: String
  markdownContent: String
  category: Category

  # Computed
  totalDuration: Int!
  userProgress: Int!
  updatedAt: DateTime
  isPurchasedByCurrentUser: Boolean!
  isCurrentUserTeacher: Boolean!

  # Relations
  teacher: User!
  chapters: [Chapter!]!
  purchases: [Purchase!]!
}

type Category {
  id: ID!
  name: String
  lessons: [Lesson!]!
}

input LessonInput {
  title: String!
  description: String
  markdownContent: String
  pictureFile: Upload

  sortedChapterIds: [String!]
}
