type Lesson {
  id: ID!
  title: String!
  "A short description of the lesson."
  description: String!
  "The URL of the cover picture of the lesson."
  pictureUrl: String
  "A description of the lesson content or presentation - in markdown format."
  markdownContent: String

  # Computed
  "Duration of the lesson in seconds."
  totalDuration: Int!
  "Completion percentage of lessons watch & quiz"
  userProgress: Int!
  "Date of the last update of a nested chapter."
  updatedAt: DateTime

  # Relations
  teacher: User!
  chapters: [Chapter!]!
}

input LessonInput {
  title: String!
  "The URL of the cover picture of the lesson."
  description: String!
  "A description of the lesson content or presentation - in markdown format."
  markdownContent: String
  "The file of the cover picture of the lesson."
  pictureFile: Upload

  sortedChapterIds: [String!]
}

# TODO: create table LessonType
