type Query {
  "Retrieves all lessons"
  lessons: [Lesson!]!

  "Retrieves a single lesson by id"
  lesson(lessonId: ID): Lesson

  "Retrieves a lesson chapter by id"
  chapter(chapterId: ID): Chapter

  "Retrieves all users"
  users: [User!]!
}
