type Query {
  "Retrieves all lessons"
  lessons: [Lesson!]!

  "Retrieves a lesson by id"
  lesson(lessonId: String!): Lesson!

  "Retrieves a lesson chapter by String"
  chapter(chapterId: String!): Chapter!

  "Retrieves all users"
  users: [User!]!

  "Retrieves a single user by id, if no id is provided, it will return the current user"
  user(userId: String): User!
}
