type Query {
  "Retrieves all lessons"
  browseLessons(category: String, search: String): [Lesson!]!

  "Retrieves all categories"
  categories: [Category!]!

  "Retrieves a lesson by id"
  lesson(lessonId: String!): Lesson!

  "Retrieves a lesson chapter by String"
  chapter(chapterId: String!): Chapter!

  "Retrieves all users"
  users: [User!]!

  "Retrieves a single user by id, if no id is provided, it will return the current user"
  user(userId: String): User!

  lessonCheckoutUrl(lessonId: String!): String!
}
