type Question {
  id: ID!
  question: String!
  answers: [String!]!
  correctAnswer: String!
}

type SubmitQuizResponse {
  isValid: Boolean!
  incorrectQuestionsId: [String!]!
}

input QuestionAnswerInput {
  questionId: String!
  answer: String!
}

input QuestionInput {
  question: String!
  answers: [String!]!
  correctAnswer: String!
}
