type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  role: Role!
  hashedPassword: String!
  lastLogin: DateTime!
  firstLogin: DateTime!

  # Relations
  createdLessons: [Lesson!]!
  comments: [Comment!]!
  purchases: [Purchase!]!

  # Computed
  fullName: String!
}

enum Role {
  ADMIN
  TEACHER
  STUDENT
}

input RegisterInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}
