query TeacherHomePage($userId: String) {
  user(userId: $userId) {
    createdLessons {
      markdownContent
      id
      description
      pictureUrl
      title
      totalDuration
      updatedAt
    }
  }
}
